// ─── PDF Report Generator ───────────────────────────────────────────
// Uses jsPDF to create professional one-page reports from engine results.
// No heavy html2canvas dependency — builds PDF programmatically.

import jsPDF from 'jspdf';
import type { EngineResult } from '@openagency/types';

// ─── Helpers ────────────────────────────────────────────────────────

function fmt(n: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: 0,
  }).format(n);
}

function pct(n: number): string {
  return `${n.toFixed(1)}%`;
}

// ─── Colors ─────────────────────────────────────────────────────────

const BRAND = [0, 119, 230] as const; // #0077e6
const DARK = [17, 24, 39] as const;
const GRAY = [107, 114, 128] as const;
const LIGHT = [243, 244, 246] as const;
const RED = [239, 68, 68] as const;
const GREEN = [34, 197, 94] as const;

// ─── Core Layout ────────────────────────────────────────────────────

function addHeader(doc: jsPDF, title: string, subtitle: string) {
  // Brand bar
  doc.setFillColor(...BRAND);
  doc.rect(0, 0, 210, 28, 'F');

  // Logo text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('OpenAgency', 14, 13);

  // Title
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(title, 14, 22);

  // Date
  doc.setFontSize(8);
  doc.text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), 196, 13, { align: 'right' });

  // Subtitle
  doc.setTextColor(...DARK);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'italic');
  doc.text(subtitle, 14, 36);
}

function addFooter(doc: jsPDF, durationMs?: number) {
  const pageHeight = doc.internal.pageSize.height;
  doc.setDrawColor(...LIGHT);
  doc.line(14, pageHeight - 14, 196, pageHeight - 14);
  doc.setTextColor(...GRAY);
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by OpenAgency | openagency.dev', 14, pageHeight - 8);
  if (durationMs != null) {
    doc.text(`Analysis: ${durationMs}ms`, 196, pageHeight - 8, { align: 'right' });
  }
}

function addSectionTitle(doc: jsPDF, y: number, title: string): number {
  doc.setTextColor(...BRAND);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 14, y);
  doc.setDrawColor(...BRAND);
  doc.line(14, y + 1.5, 196, y + 1.5);
  return y + 8;
}

function addKpi(
  doc: jsPDF,
  x: number,
  y: number,
  label: string,
  value: string,
  color: readonly [number, number, number] = DARK,
): number {
  doc.setFontSize(8);
  doc.setTextColor(...GRAY);
  doc.setFont('helvetica', 'normal');
  doc.text(label, x, y);
  doc.setFontSize(14);
  doc.setTextColor(...color);
  doc.setFont('helvetica', 'bold');
  doc.text(value, x, y + 6);
  return y + 12;
}

function addTable(
  doc: jsPDF,
  y: number,
  headers: string[],
  rows: string[][],
  colWidths: number[],
): number {
  const startX = 14;
  const rowHeight = 6;

  // Header row
  doc.setFillColor(...LIGHT);
  doc.rect(startX, y - 4, 182, rowHeight, 'F');
  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...GRAY);
  let x = startX + 2;
  for (let i = 0; i < headers.length; i++) {
    doc.text(headers[i] ?? '', x, y);
    x += colWidths[i] ?? 30;
  }
  y += rowHeight;

  // Data rows
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...DARK);
  for (const row of rows) {
    x = startX + 2;
    for (let i = 0; i < row.length; i++) {
      doc.text(row[i] ?? '', x, y);
      x += colWidths[i] ?? 30;
    }
    y += rowHeight - 1;
  }
  return y + 2;
}

// ─── Engine-specific Reports ────────────────────────────────────────

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function generateLeakDetectorReport(doc: jsPDF, result: EngineResult<any>) {
  const d = result.data;
  addHeader(doc, 'Leak Detector Report', 'Waste Waterfall Analysis');

  let y = 44;

  // KPIs
  addKpi(doc, 14, y, 'Gross Spend', fmt(d.gross_spend), DARK);
  addKpi(doc, 60, y, 'Total Waste', fmt(d.waste_summary.total_waste), RED);
  addKpi(doc, 110, y, 'Waste %', pct(d.waste_summary.waste_pct), RED);
  addKpi(doc, 156, y, 'Productive', fmt(d.productive_spend.amount), GREEN);
  y += 16;

  // Waterfall table
  y = addSectionTitle(doc, y, 'Waste Waterfall');
  const waterfallHeaders = ['Category', 'Waste Amount', 'Waste %', 'Benchmark', 'Status'];
  const waterfallRows = d.waterfall.map(
    (s: { label: string; waste_amount: number; waste_pct: number; benchmark_pct: number; vs_benchmark: string }) => [
      s.label,
      fmt(s.waste_amount),
      pct(s.waste_pct),
      pct(s.benchmark_pct),
      s.vs_benchmark,
    ],
  );
  y = addTable(doc, y, waterfallHeaders, waterfallRows, [50, 35, 25, 30, 42]);

  // Recovery roadmap
  y = addSectionTitle(doc, y + 4, 'Recovery Roadmap');
  const roadmapHeaders = ['Action', 'Category', 'Savings', 'Difficulty'];
  const roadmapRows = d.recovery_roadmap.map(
    (a: { action: string; category: string; estimated_savings: number; difficulty: string }) => [
      a.action.substring(0, 45),
      a.category,
      fmt(a.estimated_savings),
      a.difficulty,
    ],
  );
  y = addTable(doc, y, roadmapHeaders, roadmapRows, [70, 35, 35, 42]);

  // C-Suite summary
  if (d.csuite_summary && y < 240) {
    y = addSectionTitle(doc, y + 4, 'C-Suite Summary');
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...DARK);
    for (const role of ['ceo', 'cfo', 'cmo'] as const) {
      const text = d.csuite_summary[role];
      if (text && y < 270) {
        doc.setFont('helvetica', 'bold');
        doc.text(`${role.toUpperCase()}:`, 14, y);
        doc.setFont('helvetica', 'normal');
        const lines = doc.splitTextToSize(text, 155);
        doc.text(lines, 30, y);
        y += lines.length * 3.5 + 3;
      }
    }
  }

  addFooter(doc, result.duration_ms);
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function generateMediaArchitectReport(doc: jsPDF, result: EngineResult<any>) {
  const d = result.data;
  addHeader(doc, 'Media Architect Report', 'Channel Optimization Analysis');

  let y = 44;

  // KPIs
  addKpi(doc, 14, y, 'Total Budget', fmt(d.total_budget), DARK);
  addKpi(doc, 70, y, 'Allocated', fmt(d.total_allocated), BRAND);
  addKpi(doc, 130, y, 'Expected Response', d.total_expected_response.toFixed(2), GREEN);
  y += 16;

  // Channel table
  y = addSectionTitle(doc, y, 'Optimized Channel Allocation');
  const headers = ['Channel', 'Spend', '% Budget', 'Response', 'Marginal ROI', 'Saturation'];
  const rows = d.channels.map(
    (ch: { channel: string; spend: number; spend_pct: number; expected_response: number; marginal_roi: number; saturation_pct: number }) => [
      ch.channel,
      fmt(ch.spend),
      `${ch.spend_pct}%`,
      ch.expected_response.toFixed(2),
      ch.marginal_roi.toFixed(4),
      `${ch.saturation_pct}%`,
    ],
  );
  y = addTable(doc, y, headers, rows, [32, 30, 25, 30, 30, 35]);

  addFooter(doc, result.duration_ms);
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function generateMMMReport(doc: jsPDF, result: EngineResult<any>, skill: string) {
  const d = result.data;

  if (skill === 'mmm-model') {
    addHeader(doc, 'MMM Model Report', 'Marketing Mix Model Analysis');
    let y = 44;

    // KPIs
    addKpi(doc, 14, y, 'Total KPI', fmt(d.total_kpi), DARK);
    addKpi(doc, 60, y, 'Predicted KPI', fmt(d.predicted_kpi), BRAND);
    addKpi(doc, 110, y, 'R-squared', d.r_squared_estimate.toFixed(3), d.r_squared_estimate >= 0.85 ? GREEN : RED);
    addKpi(doc, 156, y, 'Overall ROI', `${d.overall_roi.toFixed(2)}x`, GREEN);
    y += 18;

    // KPI decomposition
    y = addSectionTitle(doc, y, 'KPI Decomposition');
    addKpi(doc, 14, y, 'Base (Non-Media)', fmt(d.base_contribution), GRAY);
    addKpi(doc, 80, y, 'Media Contribution', fmt(d.media_contribution), BRAND);
    addKpi(doc, 150, y, 'Media %', pct(d.media_contribution_pct), BRAND);
    y += 18;

    // Channel models table
    y = addSectionTitle(doc, y, 'Channel Model Results');
    const headers = ['Channel', 'Spend', 'Contribution', 'Share %', 'ROI', 'mROI', 'Sat.'];
    const rows = d.channel_models.map(
      (cm: { channel: string; spend: number; results: { estimated_contribution: number; contribution_share_pct: number; roi: number; marginal_roi: number; saturation_pct: number } }) => [
        cm.channel,
        fmt(cm.spend),
        fmt(cm.results.estimated_contribution),
        pct(cm.results.contribution_share_pct),
        `${cm.results.roi.toFixed(2)}x`,
        cm.results.marginal_roi.toFixed(4),
        `${cm.results.saturation_pct.toFixed(0)}%`,
      ],
    );
    y = addTable(doc, y, headers, rows, [30, 26, 28, 22, 22, 26, 28]);

    // ROI intervals
    if (d.roi_intervals && y < 220) {
      y = addSectionTitle(doc, y + 4, 'ROI with Credible Intervals');
      const riHeaders = ['Channel', 'ROI', 'Lower CI', 'Upper CI', 'mROI'];
      const riRows = d.roi_intervals.map(
        (ri: { channel: string; roi: number; lower_ci: number; upper_ci: number; mroi: number }) => [
          ri.channel,
          `${ri.roi.toFixed(2)}x`,
          `${ri.lower_ci.toFixed(2)}x`,
          `${ri.upper_ci.toFixed(2)}x`,
          ri.mroi.toFixed(4),
        ],
      );
      y = addTable(doc, y, riHeaders, riRows, [36, 36, 36, 36, 38]);
    }

    addFooter(doc, result.duration_ms);
  } else if (skill === 'mmm-optimize') {
    addHeader(doc, 'Budget Optimization Report', 'MMM Scenario Planning');
    let y = 44;

    addKpi(doc, 14, y, 'Total Budget', fmt(d.total_budget), DARK);
    if (d.comparison_vs_current) {
      addKpi(doc, 80, y, 'KPI Lift', pct(d.comparison_vs_current.kpi_lift_pct), GREEN);
      addKpi(doc, 140, y, 'ROI Improvement', `+${d.comparison_vs_current.roi_improvement.toFixed(2)}`, GREEN);
    }
    y += 18;

    // Reallocation table
    if (d.comparison_vs_current?.reallocation) {
      y = addSectionTitle(doc, y, 'Budget Reallocation');
      const headers = ['Channel', 'Current', 'Optimized', 'Delta', 'Direction'];
      const rows = d.comparison_vs_current.reallocation.map(
        (r: { channel: string; current_spend: number; optimized_spend: number; delta: number; direction: string }) => [
          r.channel,
          fmt(r.current_spend),
          fmt(r.optimized_spend),
          fmt(Math.abs(r.delta)),
          r.direction,
        ],
      );
      y = addTable(doc, y, headers, rows, [32, 34, 34, 34, 48]);
    }

    // Recommendations
    if (d.recommendations && d.recommendations.length > 0 && y < 230) {
      y = addSectionTitle(doc, y + 4, 'Recommendations');
      doc.setFontSize(7);
      doc.setTextColor(...DARK);
      for (const rec of d.recommendations) {
        if (y > 265) break;
        doc.setFont('helvetica', 'bold');
        doc.text(`[${rec.priority.toUpperCase()}]`, 14, y);
        doc.setFont('helvetica', 'normal');
        const lines = doc.splitTextToSize(`${rec.action} — ${rec.impact}`, 155);
        doc.text(lines, 32, y);
        y += lines.length * 3.5 + 3;
      }
    }

    addFooter(doc, result.duration_ms);
  } else {
    // Fallback for other MMM skills
    generateMediaArchitectReport(doc, result);
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function generateCampaignOpsReport(doc: jsPDF, result: EngineResult<any>, skill: string) {
  addHeader(doc, 'Campaign Ops Report', skill === 'campaign-create' ? 'Campaign DAG' : 'Optimization Alerts');
  let y = 44;

  if (skill === 'optimization-analyze') {
    const d = result.data;
    for (const camp of d.campaigns) {
      y = addSectionTitle(doc, y, `${camp.campaign} (${camp.channel})`);
      addKpi(doc, 14, y, 'Spend', fmt(camp.metrics.spend));
      addKpi(doc, 60, y, 'Budget', fmt(camp.metrics.budget));
      addKpi(doc, 110, y, 'CPA', fmt(camp.metrics.cpa));
      addKpi(doc, 156, y, 'ROAS', `${camp.metrics.roas.toFixed(2)}x`);
      y += 16;

      if (camp.alerts.length > 0) {
        const alertHeaders = ['Severity', 'Type', 'Message'];
        const alertRows = camp.alerts.map(
          (a: { severity: string; type: string; message: string }) => [
            a.severity.toUpperCase(),
            a.type,
            a.message.substring(0, 60),
          ],
        );
        y = addTable(doc, y, alertHeaders, alertRows, [25, 40, 117]);
      }
      y += 4;
      if (y > 250) break;
    }
  } else {
    const d = result.data;
    addKpi(doc, 14, y, 'Campaign', d.campaign.name);
    addKpi(doc, 100, y, 'Sprints', String(Object.keys(d.sprints).length));
    y += 16;

    for (const [name, sprint] of Object.entries(d.sprints) as [string, { duration_hours: number; tasks: Array<{ id: string; name: string; status: string; hours: number }> }][]) {
      y = addSectionTitle(doc, y, `${name} (${sprint.duration_hours}h)`);
      const taskHeaders = ['ID', 'Task', 'Status', 'Hours'];
      const taskRows = sprint.tasks.map((t) => [t.id, t.name.substring(0, 50), t.status, `${t.hours}h`]);
      y = addTable(doc, y, taskHeaders, taskRows, [20, 100, 30, 32]);
      y += 2;
      if (y > 250) break;
    }
  }

  addFooter(doc, result.duration_ms);
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function generateExecutiveBridgeReport(doc: jsPDF, result: EngineResult<any>, skill: string) {
  addHeader(doc, 'Executive Bridge Report', skill === 'revenue-translate' ? 'Revenue Bridge' : 'Shapley Attribution');
  let y = 44;

  if (skill === 'revenue-translate') {
    const d = result.data;
    // L1 KPIs
    y = addSectionTitle(doc, y, 'L1 Financial Metrics');
    addKpi(doc, 14, y, 'CAC', fmt(d.l1_metrics.cac));
    addKpi(doc, 50, y, 'CLV', fmt(d.l1_metrics.clv), GREEN);
    addKpi(doc, 90, y, 'CLV:CAC', `${d.l1_metrics.clv_cac_ratio.toFixed(1)}x`, d.l1_metrics.clv_cac_ratio >= 3 ? GREEN : RED);
    addKpi(doc, 130, y, 'ROI', pct(d.l1_metrics.roi_pct), GREEN);
    addKpi(doc, 165, y, 'Margin', pct(d.l1_metrics.marketing_margin_pct));
    y += 18;

    // Efficiency score
    doc.setFontSize(9);
    doc.setTextColor(...GRAY);
    doc.text(`Efficiency Score: ${d.efficiency_score}/100`, 14, y);
    y += 8;

    // Channel table
    y = addSectionTitle(doc, y, 'Channel Performance');
    const headers = ['Channel', 'CPA', 'ROAS', 'Conversions'];
    const rows = d.channels.map(
      (ch: { channel: string; l2_metrics: { cpa: number; roas: number; conversions: number } }) => [
        ch.channel,
        fmt(ch.l2_metrics.cpa),
        `${ch.l2_metrics.roas.toFixed(2)}x`,
        ch.l2_metrics.conversions.toLocaleString(),
      ],
    );
    y = addTable(doc, y, headers, rows, [45, 45, 45, 47]);

    // C-Suite
    if (d.csuite_summary && y < 230) {
      y = addSectionTitle(doc, y + 4, 'C-Suite Summary');
      doc.setFontSize(7);
      doc.setTextColor(...DARK);
      for (const role of ['ceo', 'cfo', 'cmo'] as const) {
        const text = d.csuite_summary[role];
        if (text && y < 270) {
          doc.setFont('helvetica', 'bold');
          doc.text(`${role.toUpperCase()}:`, 14, y);
          doc.setFont('helvetica', 'normal');
          const lines = doc.splitTextToSize(text, 155);
          doc.text(lines, 30, y);
          y += lines.length * 3.5 + 3;
        }
      }
    }
  } else {
    const d = result.data;
    addKpi(doc, 14, y, 'Total Conversions', d.total_conversions.toLocaleString(), BRAND);
    addKpi(doc, 80, y, 'Shapley Total', d.shapley_total.toLocaleString(), BRAND);
    y += 18;

    y = addSectionTitle(doc, y, 'Attribution Analysis');
    const headers = ['Channel', 'Shapley Value', 'Shapley %', 'Last Click %', 'Difference'];
    const rows = d.channels.map(
      (ch: { channel: string; shapley_value: number; shapley_share_pct: number; last_click_share_pct: number; difference_pct: number }) => [
        ch.channel,
        Math.round(ch.shapley_value).toLocaleString(),
        pct(ch.shapley_share_pct),
        pct(ch.last_click_share_pct),
        `${ch.difference_pct > 0 ? '+' : ''}${pct(ch.difference_pct)}`,
      ],
    );
    y = addTable(doc, y, headers, rows, [36, 36, 36, 36, 38]);
  }

  addFooter(doc, result.duration_ms);
}

// ─── Public API ─────────────────────────────────────────────────────

export function downloadReport(
  engineId: string,
  skillId: string,
  result: EngineResult<unknown>,
) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  switch (engineId) {
    case 'leak-detector':
      generateLeakDetectorReport(doc, result);
      break;
    case 'media-architect':
      if (skillId === 'mmm-model' || skillId === 'mmm-optimize') {
        generateMMMReport(doc, result, skillId);
      } else {
        generateMediaArchitectReport(doc, result);
      }
      break;
    case 'campaign-ops':
      generateCampaignOpsReport(doc, result, skillId);
      break;
    case 'executive-bridge':
      generateExecutiveBridgeReport(doc, result, skillId);
      break;
    default:
      addHeader(doc, `${engineId} Report`, skillId);
      doc.setFontSize(10);
      doc.setTextColor(...DARK);
      doc.text(JSON.stringify(result.data, null, 2).substring(0, 2000), 14, 44);
      addFooter(doc, result.duration_ms);
  }

  const timestamp = new Date().toISOString().slice(0, 10);
  doc.save(`openagency-${engineId}-${timestamp}.pdf`);
}
