-- ─── OpenAgency Phase 5: Delivery Engine File Records ───────────────
-- Stores metadata for files generated by the Delivery Engine.
-- Actual file bytes live in local filesystem (dev) or S3-compatible (prod).

CREATE TABLE IF NOT EXISTS delivery_files (
  id            TEXT PRIMARY KEY,               -- ULID
  client_id     TEXT NOT NULL,
  skill_id      TEXT NOT NULL,                  -- e.g. 'monthly-report'
  run_id        TEXT NOT NULL,                  -- mesh run that triggered this
  file_type     TEXT NOT NULL CHECK (file_type IN ('pptx', 'pdf', 'docx', 'xlsx')),
  file_path     TEXT NOT NULL,                  -- storage key (local path or S3 key)
  size_bytes    BIGINT NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at    TIMESTAMPTZ NOT NULL           -- default TTL: 90 days from created_at
);

-- Fast lookup by client (dashboard listing)
CREATE INDEX IF NOT EXISTS idx_delivery_files_client
  ON delivery_files (client_id, created_at DESC);

-- Fast lookup by run (pipeline result summary)
CREATE INDEX IF NOT EXISTS idx_delivery_files_run
  ON delivery_files (run_id);

-- Cleanup job: find expired files
CREATE INDEX IF NOT EXISTS idx_delivery_files_expires
  ON delivery_files (expires_at)
  WHERE expires_at IS NOT NULL;
